### ISSUE TITLE
How to build the apps?

### ISSUE THREAD

**Issue by joe83** [JoelSanchez/ventas#33]
how to build the apps with shadow-cljs? any instruction detail? thanks

**Comment by JoelSanchez** [comment]
Hello!

For development builds, just starting the system should be enough for shadow-cljs to be running.

For a production build, just run `npm install` followed by `lein uberjar`. The project.clj defines a prep-task for compiling the clojurescript code.

![image](https://user-images.githubusercontent.com/8020017/49328597-b31f0980-f573-11e8-87f5-2a9d84ce9aab.png)


However, I just tried with a cleanly cloned repo and it doesn't seem to work. You need to do this:
```
npm install babel-core
npm install babel-preset-env
```
This is obviously a bug and I will fix it ASAP.

Thanks!

**Comment by joe83** [comment]
got this error after 

`npm install babel-core`
`npm install babel-preset-env`
`lein uberjar`

![uberjar](https://user-images.githubusercontent.com/10484058/49340957-4c841380-f679-11e8-876d-59f38dca8bf5.png)

**Comment by joe83** [comment]
Finally make it working by add  `"src/cljs"` in :uberjar profiles.

:uberjar [:datomic-pro :build-client {:source-paths ^:replace ["src/clj" "src/cljc" "src/cljs"]

btw, after build. on browser I got almost 1366 js file downloaded. how to set the prep-task parameter to minimize the js become only 1 main.js?

**Comment by JoelSanchez** [comment]
Glad you found the problem. shadow-cljs should be doing a minified compilation already, but I'm not home right now to check. See ventas-devtools.uberjar if you want to check. I'll gladly accept a PR :)

**Comment by JoelSanchez** [comment]
I got home. So, I'm going to create a new alias for building the cljs, because using prep-tasks poses several problems:
- Including cljs source paths when in fact they aren't needed for the jar itself
- Including ventas-devtools and the cljs dependencies in the jar, when they shouldn't
Will update this task when it is done

**Comment by JoelSanchez** [comment]
Changes pushed, deployed the snapshot.
Now the command for building CLJS and SASS is `lein compile-frontend`. After that, you can call `lein uberjar`.

**Comment by JoelSanchez** [comment]
Yes, I have noticed. Some deps problem. Will take a look tomorrow

**Comment by joe83** [comment]
seems you missed some dependency, because after I run 

> lein uberjar

then run 

> lein compile 

the reader-error is gone.

but now the error change to

![ventas3](https://user-images.githubusercontent.com/10484058/49346550-ec1bc300-f6c6-11e8-8256-1f5f27279dc6.png)

**Comment by JoelSanchez** [comment]
@joe83 I did some changes to fix the dependencies. Should be working now

**Comment by JoelSanchez** [comment]
And yes I saw that error too :)

**Comment by joe83** [comment]
> @joe83 I did some changes to fix the dependencies. Should be working now

perfect.. thanks
