### ISSUE TITLE
Seeding issues

### ISSUE THREAD

**Issue by vemv** [JoelSanchez/ventas#4]
Hiya,

`(migrate-and-reindex!)` works partially on my machine.

Here's a repl session dump:

https://gist.githubusercontent.com/vemv/f1ef0f581e662718417d0837967e5a12/raw/95ebeaef691495703bda6148681f21540f0a796f/-

Two highlights:

* `DEBUG [org.elasticsearch.client.RestClient:59] - request [DELETE http://127.0.0.1:9200/ventas] returned [HTTP/1.1 404 Not Found] (migrate-and-reindex!)`
* INFO [ventas.database.seed:88] - Installing plugin :slider
clojure.lang.ExceptionInfo: Response Exception

Environment context:

* No Docker
* running plain `transactor ~/ventas/datomic/config/transactor.properties` and `elasticsearch` with no prior setup other than a stock install.

What could it be going on?

**Comment by vemv** [comment]
Btw I didn't change `:auth-secret "CHANGEME"`, don't know its purpose. Is it for cookies?

**Comment by JoelSanchez** [comment]
Ok, so, that exception is an Elasticsearch exception. Your database is fine.
Will try to investigate, but if you ran *e at the repl and showed me the stacktrace it would help a lot.

**Comment by vemv** [comment]
Here ya go: https://gist.github.com/1fdc6848c5380924c79a4d7d6deaab5c

Re: auth-secret, an alternative would be to default to nil and instruct the user to set it to something from the beginning. Losing a past value can be annoying (all sessions would get invalidated; nasty in prod) so some explicitness would seem adequate.

**Comment by JoelSanchez** [comment]
Reproduced

**Comment by JoelSanchez** [comment]
Basically I'm trying to delete the index but sometimes there's no index to delete. Will fix.
Good to default to nil on something so important to security, yep. I'll throw an exception when the value is not configured.
