### ISSUE TITLE
Images don't load after successful seeding

### ISSUE THREAD

**Issue by vemv** [JoelSanchez/ventas#5]
For each image I get a 500:

`javax.imageio.IIOException: Can't read input file!`

Perhaps they're Docker-only atm?

**Comment by JoelSanchez** [comment]
This is expected. There are no demo images in the repo. They are big and make everything worse. 
I should add a link to download them in the README. maybe as a separate repo.

**Comment by JoelSanchez** [comment]
Clone this :) https://github.com/JoelSanchez/ventas-demo-images

**Comment by vemv** [comment]
Ace! Feel free to close, will try tomorrow
